server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    contextPath: /
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/rrs-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate.ddl-auto: update
  h2:
    console.enabled: true

  logging:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error