server:
  port: 0
  servlet:
    context-path: /
  forward-headers-strategy: framework
  error:
    include-stacktrace: never

spring:
  application:
    db: gms-payment-db

openapi:
  service:
    title: GMS Payment Service
    version: 1.0
    description: Client Payment for GMS
    url: http://127.0.0.1:8060
    contact:
      name: GMS Team
      url: https://github.com/jesseballera/booking-app/tree/master/app-payment