server:
  port: 8071
  forward-headers-strategy: framework
  servlet:
    contextPath: /
  error:
    include-stacktrace: never


spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/${spring.data.mongodb.database}?authSource=${spring.data.mongodb.authentication-database}&readPreference=primaryPreferred&directConnection=true
      database: gms_customer_db
      auto-index-creation: true
      authentication-database: admin
      username: root
      password: root

io:
  reflectoring:
    kafka:
      bootstrap-servers: 'localhost:9092'
