server:
  port: 8888
  servlet:
    context-path: /
spring:
  application:
    name: configserver
  profiles:
    active: native
  output:
    ansi:
      enabled: always
  cloud:
    config:
      server:
#        git:
#          uri: https://github.com/jesseballera/gms-config.git
#          default-label: master
#          force-pull: true
    #          username: your-github-username
#          password: your-github-password
        native:
          search-locations:
            - classpath:/config
      activate:
        on-profile:
          - native
    bus:
      enabled: true
  kafka:
    bootstrap-servers:
      - localhost:9092

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){blue} %clr(${LOG_LEVEL_PATTERN:-%5p}) %m%n"