server:
  port: 8070
  forward-headers-strategy: framework
  servlet:
    contextPath: /
  error:
    include-stacktrace: never


spring:
  application:
    name: iam-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/${spring.data.mongodb.database}?authSource=${spring.data.mongodb.authentication-database}&readPreference=primaryPreferred&directConnection=true
      database: gms_iam_db
      auto-index-creation: true
      authentication-database: admin
      username: root
      password: root
