name: Java CI/CD

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag purple-mango/booking-app:${{ github.sha }}

    - name: Push to container registry
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop'
      run: |
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
#        docker tag booking-app:${{ github.sha }} purple-mango/booking-app:${{ github.sha }}
#        docker push purple-mango/booking-app:${{github.sha }}

